server {
        listen       80;
        server_name test.com;
        index index.html;
        rewrite ^ https://$server_name$request_uri? permanent;



}

server {
        listen 443 ssl http2;
        server_name test.com;
        client_max_body_size 50M;
        ssl_certificate /etc/ssl/server.crt;
        ssl_certificate_key /etc/ssl/server.key;
        include ssl_param;
        index index.html;
        root  /var/www/frontend/dist;
        try_files $uri /index.html;

        access_log /var/log/nginx/test.access.log;
        error_log /var/log/nginx/test.error.log;

        location ~ /(\.ht|Core|Specific) {
        deny all;
        return 404;
       } 

}
